/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Wla1e14QZn3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Avatar } from "@/components/ui/avatar"

export default function main() {
  return (
    <div key="1" className="flex flex-col min-h-screen">
      <header className="flex items-center h-14 border-b px-4">
        <div className="flex-1 font-semibold">Sessions</div>
        <Button className="ml-auto" size="sm" variant="outline">
          New Session
        </Button>
        <Button size="sm" variant="outline">
          New User
        </Button>
      </header>
      <div className="flex flex-1">
        <div className="w-[300px] border-r">
          <div className="flex items-center h-14 px-4 border-b">
            <SearchIcon className="mr-2 h-4 w-4 opacity-50" />
            <Input className="min-w-0" placeholder="Search sessions..." />
          </div>
          <div className="flex-1 overflow-auto">
            <nav className="px-2">
              <Button className="w-full text-left" variant="ghost">
                <div className="flex items-center gap-2">
                  <MessageSquareIcon className="w-4 h-4" />
                  <span className="font-semibold">Order #1234</span>
                </div>
                <p className="text-sm truncate w-[250px] last:mb-0">
                  {`<Message> Your order has been confirmed and will be shipped shortly.`}
                </p>
                <time className="text-sm ml-auto block">2:30pm</time>
              </Button>
              <Button className="w-full text-left" variant="ghost">
                <div className="flex items-center gap-2">
                  <MessageSquareIcon className="w-4 h-4" />
                  <span className="font-semibold">Support</span>
                </div>
                <p className="text-sm truncate w-[250px] last:mb-0">
                  {`"<Message> I\'m sorry to hear you\'re having issues with..."`}
                </p>
                <time className="text-sm ml-auto block">2:15pm</time>
              </Button>
              <Button className="w-full text-left" variant="ghost">
                <div className="flex items-center gap-2">
                  <MessageSquareIcon className="w-4 h-4" />
                  <span className="font-semibold">Feedback</span>
                </div>
                <p className="text-sm truncate w-[250px] last:mb-0">
                  {`<Message> I wanted to let you know that I really enjoyed...`}
                </p>
                <time className="text-sm ml-auto block">1:45pm</time>
              </Button>
              <Button className="w-full text-left" variant="ghost">
                <div className="flex items-center gap-2">
                  <MessageSquareIcon className="w-4 h-4" />
                  <span className="font-semibold">Promotions</span>
                </div>
                <p className="text-sm truncate w-[250px] last:mb-0">{`<Message> Check out our latest deals! 🎉`}</p>
                <time className="text-sm ml-auto block">9:00am</time>
              </Button>
              <Button className="w-full text-left" variant="ghost">
                <div className="flex items-center gap-2">
                  <MessageSquareIcon className="w-4 h-4" />
                  <span className="font-semibold">Updates</span>
                </div>
                <p className="text-sm truncate w-[250px] last:mb-0">
                  {`<Message> We will be performing maintenance on our servers...`}
                </p>
                <time className="text-sm ml-auto block">3:00pm</time>
              </Button>
            </nav>
          </div>
        </div>
        <div className="flex-1 flex flex-col">
          <div className="flex-1 p-4 bg-gray-100/40 dark:bg-gray-800/40">
            <div className="grid gap-4">
              <div className="flex items-start gap-4">
                <Avatar className="shrink-0" />
                <div className="grid gap-1">
                  <div className="bg-white border border-gray-200 rounded-lg py-4 px-4 text-sm dark:bg-gray-900 dark:border-gray-800">
                    Hi there! How can I help you today?
                  </div>
                  <time className="text-xs text-gray-500 dark:text-gray-400">Support Bot</time>
                </div>
              </div>
              <div className="flex items-end gap-4">
                <div className="grid gap-1">
                  <div className="bg-gray-100 border border-gray-200 rounded-lg py-4 px-4 text-sm dark:bg-gray-800 dark:border-gray-800">
                    I'm having trouble with my order. Can you help me?
                  </div>
                  <time className="text-xs text-gray-500 dark:text-gray-400">You</time>
                </div>
                <Avatar className="shrink-0" />
              </div>
            </div>
            <div className="mt-4 bg-gray-100/60 dark:bg-gray-800/60 p-4 rounded-lg">
              <input className="w-full p-2 rounded-md border" placeholder="Type your message here." type="text" />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function MessageSquareIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
